server:
  servlet:
    #set context-path
    context-path: /crm
    #set characterEncodingFilter
    encoding:
      charset: utf-8
      force: true

spring:
  #set jdbc parameters
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    #set thymeleaf view resolver path
    suffix: .html
    prefix: classpath:/templates/

#set mybatis
mybatis:
  #mapper save location
  mapper-locations: classpath:mapper/*.xml
  #set mybatis log
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

