#\u914D\u7F6E\u9879\u76EE\u6839\u8DEF\u5F84
server:
  servlet:
    context-path: /crm
    #配置字符集过滤器
    encoding:
      charset: utf-8
      force: true

#\u914D\u7F6E\u6570\u636E\u5E93\u4FE1\u606F
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver

#\u914D\u7F6Emybatis
mybatis:
  #\u914D\u7F6Emapper\u6587\u4EF6\u4F4D\u7F6E
  mapper-locations: classpath:mapper/*.xml
  #\u914D\u7F6E\u65E5\u5FD7
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
